### ISSUE TITLE
js可以直接操作App?

### ISSUE THREAD

**Issue by yuwade** [ZainCheung/helper-618#18]
请问大神,这是用什么框架开发的? 
界面也不错还可以打包成apk?
还有直接操作X宝App.
希望大神指点指点.

**Comment by ZainCheung** [comment]
用Autojs，使用的语言是JavaScript，另外Autojs免费版已经不再维护不过仍然是可以用的，收费的Pro版更强大，但是对黑灰产严加打击因此不能在淘宝这一类软件使用
