### ISSUE TITLE
关于浮窗的默认大小

### ISSUE THREAD

**Issue by DolphinsLoveCats** [ZainCheung/helper-618#2]
大神中午好,提一点小小的优化,在浮窗出来的以后,可能太大了,默认900 * 900的大小,可以修改大小,
console.show();
sleep(1000);
console.setSize(x00, x00);
我在写的时候发现了这样可以设置大小,其他的方式目前木有发现默认的方法.
这样写的不好就是1秒以后,在缩小.有个闪动效果....

**Comment by ZainCheung** [comment]
好的，我看了一下，是可以修改的，你说的会闪一下，可以将休眠时间降低来削弱闪动画面，10毫秒在人的眼睛里几乎是看不见的。
`console.show();
sleep(10);
console.setSize(device.width / 2, device.height / 3);`
这样确实美观了不少，也占用更小的地方，我会将这个改动加到下一版本，谢谢你的建议。。。
