### ISSUE TITLE
jd点击金币按钮

### ISSUE THREAD

**Issue by gettaken** [ZainCheung/helper-618#22]
is:issue is:open 大佬京东界面上那个金币按钮（能一直点的那个）我在代码里加了以控件ID来点击没反应能帮看下？代码如下function ClickCoin() {     if (id("goldElfin").exists()) {         log('开始点击');         id("goldElfin").findOne().click();       }      }我看了下界面上确实只有这一个ID，请问是什么问题呢，我也尝试了加入id("goldElfin").waitFor();也没效果，clickable是true，谢谢

**Comment by ZainCheung** [comment]
@gettaken 
这几天在忙论文去了，很多时候都来不及回复，不好意思啦。你的代码我测试了一下确实不行，但稍加修改后就可以用了，还有就是下次测试也要加延时，不然坑到我了（也容易坑到自己）。。。
关键代码如下（需要你到达小金人页面）：

`ClickCoin();
function ClickCoin() {
  var count = 1;//计数
  while(1){

    idContains("goldElfin").waitFor();//id改为了idContains
    log("小金人存在!");
    if (idContains("goldElfin").exists()) {
      for(var i = 0;i<5;i++){//5次点击为一周期
        idContains("goldElfin").findOne().click();
        sleep(random(201, 301));
      }
      log("第" + count + "次任务已完成");
      sleep(6 * random(1001, 1011));//大约需要6秒，小金人刷新
      count ++;
    }
  }
}`

这段代码经过测试是完全可以达到助手脚本里小金人的效果的。

**Comment by gettaken** [comment]
感谢百忙中抽空帮解决问题，谢谢
