### ISSUE TITLE
京东浏览五个商品卡住了

### ISSUE THREAD

**Issue by peiyanzhu** [ZainCheung/helper-618#23]
1.3和2.2都用了，在第一个浏览后就不动了。之前加购也不行，根据之前版主说的修改2.2的脚本加一行睡眠可以加购了。现在轮到浏览商品不行了。
![Screenshot_20200614-085649](https://user-images.githubusercontent.com/66891135/84582394-ebdfa600-adda-11ea-9550-e2041036e934.jpg)

**Comment by peiyanzhu** [comment]
![Screenshot_20200614-085649](https://user-images.githubusercontent.com/66891135/84582485-2b5ac200-addc-11ea-8d89-6080340c194e.jpg)

**Comment by ZainCheung** [comment]
因为脚本的正常执行和手机的性能以及网速什么的关系紧密，然后浏览商品前你也加睡眠试试，，不好意思一直没更新了
