### ISSUE TITLE
没红包

### ISSUE THREAD

**Issue by JhyOnya** [ZainCheung/helper-618#24]
大佬，我是自己写的脚本，没用随机数，这两天才发现用脚本升级会没有红包。请问你用随机数的版本之后，升级还能领到红包吗？
我想判断一下淘宝怎么评判脚本的，是检测是否安装autojs，还是检测是否执行脚本。
谢谢

**Comment by ZainCheung** [comment]
在一定程度上会有关系，时间随机的话应该不会被察觉到，如果时间固定的话可能就被记录下来了，然后淘宝会给你判定为机器人，我看他们说换手机登陆一下就好了，或者清除淘宝的数据然后重新登陆，然后改用随机时间版的脚本，后面应该就没事了

**Comment by JhyOnya** [comment]
我尝试网上说的，支付宝合车没有用，换手机也不行，整个人都傻眼了。
我错了我不该用脚本的，就是下次还敢。我准备双十一接着挑战极限哈哈
谢谢啊~

**Comment by ZainCheung** [comment]
哈哈，好
