### ISSUE TITLE
老哥, 你的代码怎么跟这个人的一样呢 

### ISSUE THREAD

**Issue by a2318961** [ZainCheung/helper-618#29]
https://github.com/roceys/Taobao/blob/main/%E5%90%B8%E7%8C%AB%E7%93%9C%E5%88%8620%E4%BA%BF.js

**Comment by ZainCheung** [comment]
双11我用的是上次618的脚本结构，那是五月份写的，这个人的脚本可能是基于我之前的代码改的吧
https://github.com/ZainCheung/helper-618/blob/master/src/%E6%B7%98%E5%AE%9D.js

**Comment by a2318961** [comment]
o
