### ISSUE TITLE
1.3版本不行

### ISSUE THREAD

**Issue by hhujpf** [ZainCheung/helper-618#3]
华为mate30

**Comment by ZainCheung** [comment]
1.3版本是通过测试的，并没有什么问题，如有问题可以将问题复述一下

**Comment by iloveyou616** [comment]
目前vivox21和小米6 --都是安卓9，软件可正常运行，源码代入也可正常运行，感谢分享。

**Comment by hhujpf** [comment]
应该是我的autojs版本问题,后来换了新的就可以




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "冷汐-LX"<notifications@github.com&gt;; 
发送时间: 2020年6月2日(星期二) 晚上6:04
收件人: "ZainCheung/helper-618"<helper-618@noreply.github.com&gt;; 
抄送: "季"<hhu.jpf@foxmail.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ZainCheung/helper-618] 1.3版本不行 (#3)





 
目前vivox21和小米6 --都是安卓9，软件可正常运行，源码代入也可正常运行，感谢分享。
 
&mdash;

**Comment by mswarmtree** [comment]
![Screenshot_20200603-013017](https://user-images.githubusercontent.com/57741826/83550795-faf06980-a539-11ea-96a4-2520edcdb9a9.jpg)
不知道为啥加购脚本就提示错误

**Comment by ZainCheung** [comment]
> ![Screenshot_20200603-013017](https://user-images.githubusercontent.com/57741826/83550795-faf06980-a539-11ea-96a4-2520edcdb9a9.jpg)
> 不知道为啥加购脚本就提示错误

你用的是哪个版本，是最新的1.3.0么

**Comment by hhujpf** [comment]
不是用这里的,是用的吾爱破解的最新淘宝和京东二合一的版本




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zain"<notifications@github.com&gt;; 
发送时间: 2020年6月3日(星期三) 上午8:41
收件人: "ZainCheung/helper-618"<helper-618@noreply.github.com&gt;; 
抄送: "季"<hhu.jpf@foxmail.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ZainCheung/helper-618] 1.3版本不行 (#3)





  

 不知道为啥加购脚本就提示错误
  
你用的是哪个版本，是最新的1.3.0么
 
&mdash;

**Comment by ZainCheung** [comment]
> 不是用这里的,是用的吾爱破解的最新淘宝和京东二合一的版本
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Zain"<notifications@github.com&gt;; 发送时间: 2020年6月3日(星期三) 上午8:41 收件人: "ZainCheung/helper-618"<helper-618@noreply.github.com&gt;; 抄送: "季"<hhu.jpf@foxmail.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [ZainCheung/helper-618] 1.3版本不行 (#3) 不知道为啥加购脚本就提示错误 你用的是哪个版本，是最新的1.3.0么 &mdash; You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好的，可能是速度太快导致页面控件没有加载完毕，然后识别不出来，你降低速度试试，尝鲜版的新版本已经发布了，待会我也会同步到GitHub上

**Comment by KaelInvoker** [comment]
我是用这里提供的1.3版本，确定加购脚本不行，经常卡在这个页面，识别不了。

**Comment by hhujpf** [comment]
是的,加购一次就卡住了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "KaelInvoker"<notifications@github.com&gt;; 
发送时间: 2020年6月3日(星期三) 上午10:55
收件人: "ZainCheung/helper-618"<helper-618@noreply.github.com&gt;; 
抄送: "季"<hhu.jpf@foxmail.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ZainCheung/helper-618] 1.3版本不行 (#3)





 
我是用这里提供的1.3版本，确定加购脚本不行，经常卡在这个页面，识别不了。
 
&mdash;

**Comment by KaelInvoker** [comment]
降低速度后反复测试发现，加购任务只能成功执行一次。

**Comment by FifthGently** [comment]
1.3版本 var a = text("去完成").findOnce(j); 一直返回null，one plus 7 pro，纠正后就停止了

**Comment by ZainCheung** [comment]
你们下载脚本测试一下，识别不到的话，可以试着在代码138行左右的for循环里加一行休眠

`for (var t = 0; t < 5; t++) {

      sleep(random(201, 231) * speed)//这一行是要添加的休眠，200到230毫秒

      //修复加购问题,删掉了.child(2)子节点

       idContains("cart_").findOnce(t).click();

       sleep(random(1001, 1031) * speed)
 }      `

另外我刚刚又查看了下京东最新的加购页面，也确保了代码获取的控件id不会错，有的人总是会在加购这一块出现问题，目前1.3版本也是已经解决了加购返回桌面的问题，纠正时卡在桌面，如果是第一次纠正请稍等一会，因为第一次纠正会连续返回纠正5次，在5次结束后还没有回到正确的页面时才会第二次纠正，请耐心等待一会。

**Comment by PPZPPZ** [comment]
小米6在运行8s浏览任务的时候一直要纠正，然后卡在桌面，手动进入活动界面以后，仍然是自动退出进行纠正，就这么一直循环了

**Comment by paihuai00** [comment]
1.3版本，jd加购直接卡在页面，什么都不动也不提示，等了一会也没反应....
手机型号：1+6T
