### ISSUE TITLE
京东小金人

### ISSUE THREAD

**Issue by daniel-9527** [ZainCheung/helper-618#4]
京东小金人获取位置有误，点击不到

**Comment by ZainCheung** [comment]
请问你知道怎么获取屏幕指定位置坐标么，就是在手机设置->开发者选项->指针位置，如果知道的话就方便很多了，下个版本会考虑加上自定义小金人坐标的功能

**Comment by songjiang951130** [comment]
蛋糕旁边那个人是小金人？
叠蛋糕全自动_v1.3.0.apk这个版本没有

**Comment by ZainCheung** [comment]
叠蛋糕全自动_v1.3.0.apk没有加入小金人，因为逻辑上点完小金人在去做任务太麻烦，于是就分开了，目前只加在了尝鲜版，稳定版的app后续会考虑要不要加上，但是加上后多个弹窗对用户可能就不是那么友好了
