### ISSUE TITLE
京东蛋糕旁的小人上的金币没有搜集

### ISSUE THREAD

**Issue by songjiang951130** [ZainCheung/helper-618#5]
![image](https://user-images.githubusercontent.com/20123559/83594131-01f69680-a591-11ea-8e4c-5fab1342c0ff.png)
如图

**Comment by ZainCheung** [comment]
> ![image](https://user-images.githubusercontent.com/20123559/83594131-01f69680-a591-11ea-8e4c-5fab1342c0ff.png)
> 如图
获取小金人位置时需要小金人下面有"点我得金币"这些字样，否则是识别不出来的，建议关掉京东后再使用小金人服务，这样可以确保打开后页面上小金人下面有这个字样。或者你可以勾选全自动开关，这样不需要你每次都手动打开京东小金人页面，它会自动切过去。

**Comment by songjiang951130** [comment]
> > ![image](https://user-images.githubusercontent.com/20123559/83594131-01f69680-a591-11ea-8e4c-5fab1342c0ff.png)
> > 如图
> > 获取小金人位置时需要小金人下面有"点我得金币"这些字样，否则是识别不出来的，建议关掉京东后再使用小金人服务，这样可以确保打开后页面上小金人下面有这个字样。或者你可以勾选全自动开关，这样不需要你每次都手动打开京东小金人页面，它会自动切过去。

我这个版本没有收集京东小金人，应该装哪个版本啊

**Comment by ZainCheung** [comment]
搜集小金人在尝鲜版中，目前只支持脚本运行，同时需要下载的Autojs你可以在README的链接里找到 @songjiang951130

**Comment by songjiang951130** [comment]
好的，感谢
