### ISSUE TITLE
加购任务有问题

### ISSUE THREAD

**Issue by Jessio-J** [ZainCheung/helper-618#6]
报错：
Thread[main (Spawn-0),5]:TypeError:Cannot call method "click" of null (/storage/emulated/0/脚本/618.js#573)
TypeError:Cannot call method "click" of null 
at  /storage/emulated/0/脚本/618.js#573:0
at /storage/emulated/0/脚本/618.js#516:0

**Comment by ZainCheung** [comment]
> 报错：
> Thread[main (Spawn-0),5]:TypeError:Cannot call method "click" of null (/storage/emulated/0/脚本/618.js#573)
> TypeError:Cannot call method "click" of null
> at /storage/emulated/0/脚本/618.js#573:0
> at /storage/emulated/0/脚本/618.js#516:0

你好，可以参考这条issue：
https://github.com/ZainCheung/helper-618/issues/3#issuecomment-637928373
