### ISSUE TITLE
加购无效

### ISSUE THREAD

**Issue by xiaoyulei** [ZainCheung/helper-618#8]
进入后没有任何反应

**Comment by ZainCheung** [comment]
正式版的app和脚本以及集成尝鲜版在今天的测试中都是可以正常运行的，如果加购无效建议在尝鲜版中取消加购选项的勾选。
另外如果使用的是脚本，可以尝试着自行修改相关代码，利用Autojs软件可以查看京东的页面布局。如果是因为软件版本不同导致的问题还请将京东升级至最新版，autojs升级至项目推荐的版本。

**Comment by xiaoyulei** [comment]
> 正式版的app和脚本以及集成尝鲜版在今天的测试中都是可以正常运行的，如果加购无效建议在尝鲜版中取消加购选项的勾选。
> 另外如果使用的是脚本，可以尝试着自行修改相关代码，利用Autojs软件可以查看京东的页面布局。如果是因为软件版本不同导致的问题还请将京东升级至最新版，autojs升级至项目推荐的版本。

正式版app和脚本是只哪个？我用的就是下面这个这个，有问题：
```
淘宝+京东集成尝鲜版脚本
蓝奏云地址：https://zaincheung.lanzous.com/b00tl6x1g 密码:bed2
```

**Comment by ZainCheung** [comment]
@xiaoyulei 
正式版是指已经打包为app的那俩，一个是叠蛋糕，一个是淘宝列车，你打开就看到了
https://github.com/ZainCheung/helper-618#%E4%B8%8B%E8%BD%BD%E5%9C%B0%E5%9D%80

**Comment by xiaoyulei** [comment]
> @xiaoyulei
> 正式版是指已经打包为app的那俩，一个是叠蛋糕，一个是淘宝列车，你打开就看到了
> https://github.com/ZainCheung/helper-618#%E4%B8%8B%E8%BD%BD%E5%9C%B0%E5%9D%80

我用的你这个里面的叠蛋糕源码在autojs里面跑，一样出错

**Comment by xuyuxcc** [comment]
加购无效的问题，查看日志是TypeError:Cannot call method "click" of null  应该是前面的对象没有获取到，报空指针了，望修复

**Comment by MichaelZys** [comment]
> 正式版的app和脚本以及集成尝鲜版在今天的测试中都是可以正常运行的，如果加购无效建议在尝鲜版中取消加购选项的勾选。
> 另外如果使用的是脚本，可以尝试着自行修改相关代码，利用Autojs软件可以查看京东的页面布局。如果是因为软件版本不同导致的问题还请将京东升级至最新版，autojs升级至项目推荐的版本。

请问怎么看京东的页面布局. 小白请教.

**Comment by ZainCheung** [comment]
> > 正式版的app和脚本以及集成尝鲜版在今天的测试中都是可以正常运行的，如果加购无效建议在尝鲜版中取消加购选项的勾选。
> > 另外如果使用的是脚本，可以尝试着自行修改相关代码，利用Autojs软件可以查看京东的页面布局。如果是因为软件版本不同导致的问题还请将京东升级至最新版，autojs升级至项目推荐的版本。
> 
> 请问怎么看京东的页面布局. 小白请教.

打开Autojs的悬浮窗，在悬浮窗里面有个布局分析

**Comment by xiaoyulei** [comment]
close after of #12 #13 #14 #15
